version: 2.1

aliases:
  - &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - lib

  test-re-bs:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test with react
          command: |
            set -x
            yarn install
            yarn go "ReasonML Bucklescript" test y
            cd out
            yarn test
            cd ..
            rm -rf out
      - run:
          name: Test without react
          command: |
            set -x
            yarn install
            yarn go "ReasonML Bucklescript" test n
            cd out
            yarn test
            cd ..
            rm -rf out

workflows:
  version: 2
  main:
    jobs:
      - build
      - test-re-bs:
          requires:
            - build
