version: 2.1

aliases:
  - &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test-re-bs:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test with react
          command: |
            .circleci/test.sh "ReasonML Bucklescript" test y
      - run:
          name: Test without react
          command: |
            .circleci/test.sh "ReasonML Bucklescript" test n

workflows:
  version: 2
  main:
    jobs:
      - build
      - test-re-bs:
          requires:
            - build
