version: 2

aliases:
  - &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:10

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT: 'reports/jest/jest.xml'
      - store_test_results:
          path: reports

  # storybook:
  #   <<: *defaults
  #   steps:
  #     # TODO: publish to github or s3 here
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: Generate Storybook
  #         command: |
  #           rm -rf docs/storybook
  #           yarn storybook:build

  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint

workflows:
  version: 2
  main:
    jobs:
      - install
      - test:
          requires:
            - install
      - lint:
          requires:
            - install
      # - storybook:
      #     requires:
      #       - install
